- name: Configure Maven settings.xml for Nexus
        run: |
          mkdir -p ~/.m2
          cat << 'EOF' > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" 
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
              <servers>
                  <server>
                      <id>nexus</id>
                      <username>${env.NEXUS_USER}</username>
                      <password>${env.NEXUS_PASSWORD}</password>
                  </server>
              </servers>
              
              <profiles>
                  <profile>
                      <id>nexus</id>
                      <repositories>
                          <repository>
                              <id>nexus-public</id>
                              <url>http://localhost:8081/repository/maven-public/</url>
                              <releases><enabled>true</enabled></releases>
                              <snapshots><enabled>true</enabled></snapshots>
                          </repository>
                      </repositories>
                      <pluginRepositories>
                          <pluginRepository>
                              <id>nexus-public</id>
                              <url>http://localhost:8081/repository/maven-public/</url>
                              <releases><enabled>true</enabled></releases>
                              <snapshots><enabled>true</enabled></snapshots>
                          </pluginRepository>
                      </pluginRepositories>
                  </profile>
              </profiles>
              <activeProfiles>
                  <activeProfile>nexus</activeProfile>
              </activeProfiles>
          </settings>
          EOF